services:
  - type: web
    name: freshmart-api
    env: python
    buildCommand: pip install -r requirements.txt
    releaseCommand: flask db upgrade
    startCommand: gunicorn run:app
    healthCheckPath: /api/products
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: run.py